// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCarTelemetry() {
  return window['go']['telemetry']['Telemetry']['GetCarTelemetry']();
}

export function GetCode() {
  return window['go']['telemetry']['Telemetry']['GetCode']();
}

export function GetSpeed() {
  return window['go']['telemetry']['Telemetry']['GetSpeed']();
}
