// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FramesJSON() {
  return window['go']['telemetry']['Telemetry']['FramesJSON']();
}

export function GetCode() {
  return window['go']['telemetry']['Telemetry']['GetCode']();
}
