// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {packets} from '../models';

export function GetCarTelemetry():Promise<packets.CarTelemetryData>;

export function GetCode():Promise<string>;

export function GetSpeed():Promise<number>;
