// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCode() {
  return window['go']['main']['Telemetry']['GetCode']();
}

export function GetSpeed() {
  return window['go']['main']['Telemetry']['GetSpeed']();
}
